// build.rs

fn main() {
    cxx_build::bridge("src/lib.rs")
        .include("deps/Fairy-Stockfish-Lib/src")
        .include("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src")
        .define("NNUE_EMBEDDING_OFF", Some("0"))
        .define("LARGEBOARDS", Some("0"))
        .define("PRECOMPUTED_MAGICS", Some("0"))
        .file("src/fairystockfishrs.cpp")
        .file("deps/Fairy-Stockfish-Lib/src/fairystockfish.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/benchmark.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/bitbase.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/bitboard.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/endgame.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/evaluate.cpp")
        //.file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/main.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/material.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/misc.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/movegen.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/movepick.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/nnue/evaluate_nnue.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/nnue/features/half_ka_v2.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/nnue/features/half_ka_v2_variants.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/parser.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/partner.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/pawns.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/piece.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/position.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/psqt.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/search.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/syzygy/tbprobe.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/thread.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/timeman.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/tt.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/tune.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/uci.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/ucioption.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/variant.cpp")
        .file("deps/Fairy-Stockfish-Lib/vendor/Fairy-Stockfish/src/xboard.cpp")
        .flag_if_supported("-std=c++17")
        .compile("fairystockfish");
}
